sudo: false
language: node_js
node_js:
  - 6
  - 8
  - 10
after_success:
  - npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 2307......f4ea
    secure: A5FRKdPID/XEKiTEiIV/jhRrqm/xk/7kDsOE1UlGpZzHvXUyF7H7678KEXItrw1266Dqeu7Pot3Tb6t4lp8NSoPJmG1uAHANRovu54FI6U1xffp/v+p2Lpo8NIl8axG3E/4++27nBTNny24znD4dX52032Ct698nJuxShbMUfVpwmKovegvDvitmQ6VvywmUnzS5vAl34ZzNd0UIKS4Hduqi7lsj5e0hrjgUikKF9koo7s3zY3JPFgPYSbFnrIOYre7SAWx58AMmKySy9cjpwnHG4QX/6Iu6dUOU3AMHRJYHyLEVdLxvgCkB5pO5HlQlJ/ktR3lu2mC1CmJqIM96E2MffT1ZvVWn1lW00KsJx7qnRqErBst5lTO2r6Xm7N77mIZdAx3+5oV7/pmEw/abVje40oqEu7CDPxJB8bQ+5KFmaoMyNGr0dSMG7/ID6fZTFGh6/jvb04O8dSgHynfAWjGgofM9Wfr7q/4DZqI+CdFCGn7sPvyuaHN5Yx5p38dEyaHK7tUEIpq8FuuN2JSvWpm1WUXzCRqlIKlmjB+laHKk/GBc42Robb7OHC/mjNv7hoNDWNl5lmUzApxlkFCd764AETsBv5zFMovXP2kLnyPjGTtrUeapmHk4yO7gi4uusDCRDR5xIVWQHxhUA9/cNIYgr3h65sTRQtDXy1xGvlA=
  on:
    tags: true
    repo: Brightspace/node-valence-url
    node: 10
